data:extend({
  {
		type = "string-setting",
		name = "bzchlorine-recipe-bypass",
		setting_type = "startup",
		default_value = "",
    allow_blank = true,
    order = "a",
	},
  {
		type = "bool-setting",
		name = "bzchlorine-list",
		setting_type = "startup",
    default_value = false,
    order = "b",
	},
  {
    type = "bool-setting",
    name = "bzchlorine-salt",
		setting_type = "startup",
    default_value = true,
    order = "c1",
  },
  {
		type = "string-setting",
		name = "bzchlorine-early-salt",
		setting_type = "startup",
		default_value = "assembler",
    allowed_values = {"assembler", "mining", "both"},
    order = "c2",
	},
  {
		type = "string-setting",
		name = "bzchlorine-more-intermediates",
		setting_type = "startup",
		default_value = "yes",
    allowed_values = {"yes", "no"},
    order = "d",
	},
})
